//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSON.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSON.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_schema&quot; : {
        ///        &quot;Banner Image&quot; : {
        ///            &quot;_type&quot; : &quot;File&quot;
        ///        },
        ///        &quot;Gem Image&quot; : {
        ///            &quot;_type&quot; : &quot;File&quot;
        ///        },
        ///        &quot;Image&quot; : {
        ///            &quot;_type&quot; : &quot;File&quot;
        ///        },
        ///        &quot;GEMICON01&quot; : {
        ///            &quot;_type&quot; : &quot;File&quot;
        ///        },
        ///        &quot;GEMICON02&quot; : {
        ///            &quot;_type&quot; : &quot;File&quot;
        ///        },
        ///        &quot;GEMICON03&quot; : {
        ///            &quot;_type&quot; : &quot;File&quot;
        ///        },
        ///        &quot;GEMICON04&quot; : {
        ///            &quot;_type&quot; : &quot;File&quot;
        ///        },
        ///        &quot;GEMICONMany&quot; : {
        ///            &quot;_type&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JSONLPVarTest {
            get {
                return ResourceManager.GetString("JSONLPVarTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Machine&quot; : {
        ///        &quot;color&quot;: &quot;38,61,10&quot;,
        ///        &quot;Name&quot;: &quot;Farm&quot;,
        ///        &quot;ID&quot;: &quot;11&quot;,
        ///        &quot;UnlockLevel&quot;: &quot;1&quot;,
        ///        &quot;MinBet&quot;: &quot;30&quot;,
        ///        &quot;MaxLines&quot;: &quot;15&quot;,
        ///        &quot;Symbols&quot;: {
        ///            &quot;Symbol0&quot;: {
        ///                &quot;MatchMultipliers&quot;: &quot;0,0,2.1,11,55&quot;,
        ///                &quot;Weight&quot;: &quot;90&quot;
        ///            },
        ///            &quot;Symbol1&quot;: {
        ///                &quot;MatchMultipliers&quot;: &quot;0,0,3.3,17,60&quot;,
        ///                &quot;Weight&quot;: &quot;86&quot;
        ///            },
        ///            &quot;Symbol2&quot;: {
        ///                &quot;MatchMultipliers&quot;: &quot;0,0,4.4,22 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JSONSLotsFarmTest {
            get {
                return ResourceManager.GetString("JSONSLotsFarmTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;StartingCoinBalance&quot;: 5000,
        ///	&quot;BaseExperience&quot;: 2,
        ///    &quot;MinSpinXP&quot; : 50,
        ///    &quot;MaxSpinXP&quot; : 100,
        ///	&quot;BonusExperienceRate&quot;: 1,
        ///	&quot;ExperiencePerLevel&quot;: {
        ///		&quot;2&quot;: 4000,
        ///		&quot;3&quot;: 8000,
        ///		&quot;4&quot;: 12000,
        ///		&quot;5&quot;: 20000,
        ///		&quot;6&quot;: 24000,
        ///		&quot;7&quot;: 30000,
        ///		&quot;8&quot;: 35000,
        ///		&quot;9&quot;: 38000,
        ///		&quot;10&quot;: 40000,
        ///		&quot;11&quot;: 50000,
        ///		&quot;12&quot;: 60000,
        ///		&quot;13&quot;: 70000,
        ///		&quot;14&quot;: 80000,
        ///		&quot;15&quot;: 90000,
        ///		&quot;16&quot;: 100000,
        ///		&quot;17&quot;: 110000,
        ///		&quot;18&quot;: 113114,
        ///		&quot;19&quot;: 76870,
        ///		&quot;20&quot;: 91413,
        ///		&quot;21&quot;: 139168,
        ///		&quot;22&quot;: 94128,
        ///		&quot;23&quot;: 142868,
        ///		&quot;24&quot;: 193570,
        ///		&quot;25&quot;: 147144,
        ///		&quot;2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JSONSlotsGameDefaultsTest {
            get {
                return ResourceManager.GetString("JSONSlotsGameDefaultsTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Paylines&quot;: {
        ///        &quot;Line 1&quot;: {
        ///            &quot;Positions&quot;: &quot;1,1,1,1,1&quot;,
        ///            &quot;Offsets&quot;: &quot;0,0,0,0,0&quot;,
        ///            &quot;Color&quot;: {
        ///                &quot;Red&quot;: 1,
        ///                &quot;Green&quot;: 0.09,
        ///                &quot;Blue&quot;: 0.259,
        ///                &quot;Alpha&quot;: 1
        ///            },
        ///            &quot;Drawn From Left&quot;: true
        ///        },
        ///        &quot;Line 2&quot;: {
        ///            &quot;Positions&quot;: &quot;0,0,0,0,0&quot;,
        ///            &quot;Offsets&quot;: &quot;0,0,0,0,0&quot;,
        ///            &quot;Color&quot;: {
        ///                &quot;Red&quot;: 0,
        ///                &quot;Green&quot;: 0.945,
        ///                &quot;Blue&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JSONSlotsPayLineTest {
            get {
                return ResourceManager.GetString("JSONSlotsPayLineTest", resourceCulture);
            }
        }
    }
}
